server:
  port: 80
eureka:
  client:
    registerWithEureka: false # 服务注册，false表示不将本消费者注册到 Eureka 服务器
    fetchRegistry: true # 服务发现，true从 Eureka 服务器中获取注册信息
    serviceUrl:
      defaultZone: http://127.0.0.1:6001/eureka/,http://127.0.0.1:6002/eureka/
# 在Feign中需要开启 Hystrix
feign:
  httpclient:
    connection-timeout: 3000
  hystrix:
    enabled: true
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
ribbon:
  eureka:
    enabled: true
